### ISSUE TITLE
converting to exe

### ISSUE THREAD

**Issue by famko09** [kethan1/WinTmp#2]
Hi there,
i was  testing your script. It works fine within Visual Code studio. But when i convert it to an exe , it is not working at all. i see a flash of a screen, and that is all. Here is the pyton script i am usning: 
```
import time
import WinTmp  # Ensure this module is correctly installed or accessible

# File path for storing CPU temperature data
file_path = 'cpu_temp.log'

def print_cpu_temp():
    while True:
        try:
            temp = WinTmp.CPU_Temp()  # Attempt to fetch the current CPU temperature
            with open(file_path, 'a') as file:
                file.write(f"CPU Temp: {temp}°C\n")  # Write the temperature to the file
            print(f"CPU Temp: {temp}°C")  # Print the temperature to the console
        except Exception as e:
            print(f"Failed to update temperature: {e}")  # Print any errors
        time.sleep(1)  # Wait for 1 second before fetching the temperature again

if __name__ == "__main__":
    try:
        print_cpu_temp()
    except KeyboardInterrupt:
        print("Application stopped by user.")
    except Exception as e:
        print(f"Application failed: {e}")
```

**Comment by kethan1** [comment]
Thank you for filing an issue. 

How are you converting the script to an exe? Are you using PyInstaller or another tool?

**Comment by famko09** [comment]
Auto-py-to-exexMvg Will KostonsOp 1 apr 2024 om 19:40 heeft Kethan Vegunta ***@***.***> het volgende geschreven:﻿
Thank you for filing an issue and using WinTmp.
How are you converting the script to an exe? Are you using PyInstaller or another tool?

**Comment by kethan1** [comment]
Looking at Auto-PY-to-EXE's Github page, it appears that it is just a graphical wrapper around PyInstaller. 

Using PyInstaller, I followed these steps:
```
1. Create a folder named test (`mkdir test`, can be named anything).
2. Create a file named `main.py` (can be named anything) and paste your code from above into the file.
3. Install PyInstaller and WinTmp (`pip install pyinstaller wintmp`)
4. Run `pyinstaller -F main.py --collect-binaries WinTmp`.
5. `cd dist`
6. `./main.exe`
```

And the code worked as expected. Could you try to follow these steps and see if you can generate a usable `exe`?

**Comment by famko09** [comment]
Thanks for answering,

this works, but why is it not working with Auto-py-to-exex, all my other scripts are....

**Comment by kethan1** [comment]
WinTmp internally uses LibreHardwareMonitor in the form of a DLL file. I believe your initial attempt at packaging your application into an exe didn't not succeed due to PyInstaller not bundling this required file. I am not the most familiar with PyInstaller, but it appears it needed to be told what files to package, therefore the option `--collect-binaries WinTmp` (there are other options for non-binary files, [see this](https://stackoverflow.com/a/73547165/13710015)) needed to be added. 

As mentioned above, Auto-PY-to-EXE appears to be a graphical wrapper around PyInstaller. You might be able to add the `--collect-binaries WinTmp` in the GUI of Auto-PY-to-EXE (maybe in advanced options).

Given the fact that this issue was resolved, I will be closing. If it continues to persist, feel free to add a comment with further clarification or reopen the issue.
